config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
  resources :bands
  resources :albums, only: [:create, :new, :update, :edit, :destroy, :show]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  band_id    :integer          not null
#  year       :integer          not null
#  studio     :boolean          default(TRUE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :title, :year, :studio, presence: true

  belongs_to :band,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: 'Band'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: 'Album'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true

  validates :password, length: {minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token


  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      @band = @album.band
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def new
    @album = Album.new(band_id: params[:band_id])
    @band = Band.find(params[:band_id])

    render :new
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_url
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end

  end

  private
  def album_params
    params.require(:album).permit(:title, :year, :studio, :band_id)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception


  helper_method :current_user
  helper_method :logged_in?

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def create
    @band = Band.new(band_param)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    #if @band.update(band_param)
    if @band.update_attributes(band_param)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private
  def band_param
    params.require(:band).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:email],params[:user][:password])

    if user.nil?
      flash.now[:errors] = ["incorrect email or password"]
      render :new
    else
      login!(user)
      #redirect_to users show users_url
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to new_session_url
    else
      flash.now[:errors] = @user.erros.full_messages
      render :new
    end
  end

  def show
    render :show
  end


  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input
      type='hidden'
      name='authenticity_token'
      value='#{form_authenticity_token}'>".html_safe
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/new.html.erb
<h1>Create a new album</h1>

<form class="" action=" <%= albums_url %> " method="POST">

  <label for="album_title">title</label>
  <input
  id="album_title"
  type="text"
  name="album[title]"
  value="<%= @album.title %> ">
  <p>
    <label for="album_band">Band</label>
    <select id="album_band" name="album[band_id]">
      <% Band.all.each do |band| %>
      <option
        <%= "selected" if @album.band_id == band.id  %>
        value = " <%= band.id %> "
        <%= band.name %>
      </option>
      <% end %>
    </select>
  </p>

  <label for="album_year">year</label>
  <input
    id="album_year"
    type="text"
    name="album[year]"
    value="<%= @album.year %> ">

  <label for="album_studio">Studio</label>
  <input
    id="album_studio"
    type="radio"
    name="album[studio]"
    value="t"
    <%= "checked" if @album.studio  %>>
  <label for="album_live">Live</label>
  <input
  id="album_live"
  type="radio"
  name="album[studio]"
  value="f"
  <%= "checked" if !@album.studio %> >


  <input type="submit">

</form>

app/views/albums/show.html.erb
<h3> <%= @album.title %> </h3>

app/views/bands/index.html.erb
<h1>Here is the list of all the bands</h1>

<p>
  <% @bands.each do |band| %>
   <li><%= band.name %></li>  
  <% end %>
</p>

app/views/bands/new.html.erb
<h1>Create a new band</h1>

<form class="" action=" <%= bands_url %> "method="post">
  <label for="band_name">Name</label>
  <input id="band_name" type="text" name="band[name]" value="<%= @band.name %>">

  <input type="submit">

</form>

app/views/bands/show.html.erb
<h3> <%= @band.name %> </h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <header>
    <div>
      <% if current_user.nil? %>
        <%= link_to 'Sign up', new_user_url %>
        <%= link_to 'Sign in', new_session_url %>
      <% else %>
        <%= current_user.email %>
        <%= button_to 'Logout', session_url, method: :delete %>
      <% end %>
    </div>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<section>
  <div class="">
    <h1>New User</h1>
    <form class="" action=" <%= users_url %> " method="post">
      <%= auth_token %>
      <label for="user_email">Email</label>
      <input type="text" id="user_email" name="user[email]" value=" <%= @user.email %> ">
      <br>
      <label for="user_password">Password</label>
      <input type="password" id="user_password" name="user[password]" value="<%= @user.password %>">
      <br>
      <input type="submit">

    </form>
  </div>
</section>

app/views/users/show.html.erb
<h1>Hello! Thank you for signing up</h1>